version: "1.0.1"

services:
    src1:
        image: nginx:latest
        networks:
            - my_network
        container_name: src1
        hostname: service1
        command: /bin/bash -c "echo 'Connected to svc1' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

    src2:
        image: nginx:latest
        networks:
            - my_network
        container_name: src2
        hostname: service2
        command: /bin/bash -c "echo 'Connected to svc2' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"

networks:
    my_network:
        driver: bridge
